// Created by Crowbar 0.57

$modelname "c:/sierra/half-life/valve/models/w_357.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_357_w_python_reference"
}

$flags 0

$texturegroup "skinfamilies"
{
	{
		"w_python_reference.bmp"
	}
}


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Cylinder01" -1.53 -7.42 -6.06 1.5 2.53 13.32

$sequence "position" {
	"w_357_anims\position"
	fps 30
}
